  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install dependencies
        run: |
          sudo gem install cocoapods
          pod install || true
          gem install xcpretty

      - name: Build and Test
        run: |
          set -o pipefail && 
          xcodebuild clean build test \
            -project HelloWorldApp.xcodeproj \
            -scheme HelloWorldApp \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.1' \
            CODE_SIGNING_ALLOWED=NO | xcpretty

      - name: Save Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
