name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install dependencies
        run: |
          sudo gem install cocoapods
          pod install || true
          gem install xcpretty

      - name: Build and Test
        run: |
          set -eo pipefail &&
          xcodebuild clean build test \
            -project HelloWorld.xcodeproj \
            -scheme HelloWorld \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            -derivedDataPath Build/DerivedData \
            CODE_SIGNING_ALLOWED=NO \
            -enableCodeCoverage YES | xcpretty

      - name: Check Test Results
        run: |
          TEST_RESULTS=$(find Build/DerivedData -name "*.xcresult")
          echo "Test results found at: $TEST_RESULTS"
          if [ -z "$TEST_RESULTS" ]; then
            echo "No test results found!"
            exit 1
          fi
          xcrun xcresulttool get --path "$TEST_RESULTS" --format json > results.json
          if grep -q '"failureSummaries"' results.json; then
            echo "Tests failed!"
            exit 1
          fi

      - name: Save Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: Build/DerivedData/**/Logs/Test/*.xcresult